tasks:
  build-deps:
    #runner: razorci/python:3.9
    #runner: razorci/openjdk
    steps:
    - checkout
    - commands:
    - run: pip install pytest
    - run: pip freeze --local > api/requirements.txt
    - run: pip install pytest-cov
    - run: pytest --cov app/ --cov-report=xml:test-coverage.xml
    - codecov/upload 
    - run: |
           curl -Os https://uploader.codecov.io/latest/linux/codecov
           chmod +x codecov
           ./codecov -t ${CODECOV_TOKEN} 
