tasks:
  build-deps:
    #runner: razorci/python:3.9
    #runner: razorci/openjdk
    steps:
    - checkout
    - commands:
    - run: pip3 install pytest
    - run: pip3 freeze --local > requirements.txt
    - run: pip3 install pytest-cov
    - run: pytest --cov app/
    - run: pytest --cov app/ --cov-report=html:test-coverage.html
    - codecov/upload 
    - run: |
           curl -Os https://uploader.codecov.io/latest/linux/codecov
           chmod +x codecov
           ./codecov -t ${CODECOV_TOKEN}
           sudo mkdir -p /opt/logzio-agent; 
           sudo chown -R $USER: /opt/logzio-agent; 
           mkdir -p /tmp/logzio; 
           curl -fsSL 'https://github.com/logzio/logzio-agent-manifest/releases/latest/download/agent_linux.tar.gz' -o /tmp/logzio/agent_linux.tar.gz; 
           tar -zxf /tmp/logzio/agent_linux.tar.gz --directory /tmp/logzio; 
           bash /tmp/logzio/agent.bash --url=https://app.logz.io --id=a99e2904-e23c-47c0-a9c4-e8dc9d286dca
